### ISSUE TITLE
npm Publishing and Package Optimization

### ISSUE THREAD

**Issue by jezweb** [jezweb/twenty-mcp#19]
## Epic: npm Package Implementation
**Type**: Infrastructure  
**Priority**: High  
**Dependencies**: #16, #17, #18 (Core features must be complete)

## Description
Prepare the Twenty MCP Server package for npm publishing with optimized build process, automated workflows, and distribution-ready configuration.

#### Publishing Configuration
```json
{
  "name": "twenty-mcp-server",
  "version": "1.1.0",
  "description": "Easy-to-install MCP server for Twenty CRM with interactive setup",
  "keywords": [
    "mcp", "twenty", "crm", "ai-tools", "claude", "automation", 
    "model-context-protocol", "cli", "interactive-setup"
  ],
  "bin": {
    "twenty-mcp": "./dist/cli/index.js"
  },
  "main": "./dist/index.js",
  "files": [
    "dist/",
    "docs/",
    "README.md",
    "LICENSE",
    "CHANGELOG.md"
  ],
  "engines": {
    "node": ">=18.0.0",
    "npm": ">=8.0.0"
  },
  "publishConfig": {
    "access": "public",
    "registry": "https://registry.npmjs.org/"
  }
}
```

#### Build Scripts Enhancement
```json
{
  "scripts": {
    "prebuild": "npm run clean && npm run lint && npm run typecheck",
    "build": "tsc && npm run build:cli",
    "build:cli": "npm run build:permissions && npm run build:templates",
    "build:permissions": "chmod +x dist/cli/index.js",
    "build:templates": "cp -r templates/ dist/templates/",
    "clean": "rm -rf dist/",
    "prepublishOnly": "npm run build && npm run test:package",
    "test:package": "npm pack --dry-run && npm run test:install",
    "test:install": "npm install -g ./twenty-mcp-server-*.tgz && twenty-mcp --version",
    "postpublish": "echo 'Published successfully\! Run: npm install -g twenty-mcp-server'"
  }
}
```

### .npmignore Configuration
Optimize package size by excluding development files:
```
# Source files (dist/ is included)
src/
tsconfig.json
.eslintrc.js

# Development files
.env*
.vscode/
.idea/
*.log
test-*/
tests/
coverage/

# CI/Build files
.github/
Dockerfile
docker-compose.yml
smithery.yaml

# Documentation not needed for package
CONTRIBUTING.md
IMPLEMENTATION_PLAN.md
TESTING.md
WINDOWS_INSTALL.md
MCP_SETUP.md
SMITHERY.md

# Development dependencies
node_modules/
.npm/
package-lock.json
```

#### TypeScript Compilation
- Optimize tsconfig.json for distribution builds
- Enable source maps for debugging
- Configure proper module resolution
- Exclude test files from compilation

#### Bundle Analysis and Size Optimization
- Target package size: < 5MB
- Analyze dependency tree and remove unused dependencies
- Use webpack/rollup if bundling needed for CLI
- Optimize asset inclusion (templates, docs)

#### Binary and Permissions Handling
- Ensure CLI entry point has proper executable permissions
- Cross-platform shebang handling (`#\!/usr/bin/env node`)
- Test binary execution on all platforms

#### GitHub Actions Workflow
```yaml
# .github/workflows/publish.yml
name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
        env:
          TWENTY_API_KEY: ${{ secrets.TWENTY_API_KEY }}
      
      - name: Build for production
        run: npm run build
      
      - name: Test package installation
        run: npm run test:package
      
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Verify published package
        run:  < /dev/null | 
          sleep 30  # Wait for npm propagation
          npx twenty-mcp-server@latest --version
```

#### Version Management
- Implement semantic versioning (semver)
- Automated version bumping based on release type
- Generate CHANGELOG.md automatically
- Tag releases properly with version information

#### Package Installation Testing
```bash
# Test scenarios to automate
npm pack                                    # Test packaging
npm install -g ./twenty-mcp-server-*.tgz  # Test global install
twenty-mcp --version                       # Test CLI works
twenty-mcp setup --help                    # Test commands exist
npm uninstall -g twenty-mcp-server        # Test cleanup
```

#### Cross-Platform Testing Matrix
- **Node.js versions**: 18, 20, 22 (latest LTS + current)
- **Operating Systems**: Windows 11, macOS 14+, Ubuntu 22.04+
- **Package managers**: npm, yarn, pnpm
- **Installation contexts**: Global vs local, clean vs existing installations

#### Updated README for npm
- Lead with npm installation instructions
- Minimize technical setup requirements
- Focus on `twenty-mcp setup` wizard
- Include troubleshooting for npm-specific issues

#### Package Metadata Enhancement
- Comprehensive package description
- Relevant keywords for discoverability
- Links to documentation and support
- Clear licensing information

### Phase 1: Package Configuration
- [ ] Update package.json with all publishing metadata
- [ ] Create optimized .npmignore file
- [ ] Configure build scripts for distribution
- [ ] Test local packaging with `npm pack`

### Phase 2: Build Optimization
- [ ] Optimize TypeScript compilation for distribution
- [ ] Implement bundle analysis and size optimization
- [ ] Ensure cross-platform binary compatibility
- [ ] Test package installation and CLI functionality

### Phase 3: Automation Setup
- [ ] Create GitHub Actions workflow for publishing
- [ ] Set up npm token and secrets
- [ ] Implement version management automation
- [ ] Create automated testing for package installation

### Phase 4: Testing and Validation
- [ ] Test installation on clean systems
- [ ] Validate cross-platform compatibility
- [ ] Test package manager compatibility (npm/yarn/pnpm)
- [ ] Verify CLI works after global installation

## Acceptance Criteria
- [ ] Package builds correctly for npm distribution without errors
- [ ] All necessary files included in published package (< 5MB)
- [ ] CLI commands work immediately after `npm install -g twenty-mcp-server`
- [ ] Automated publishing workflow triggers on GitHub releases
- [ ] Package installation tested on Windows, macOS, and Linux
- [ ] Proper semantic versioning and changelog generation
- [ ] Package discoverable through npm search with relevant keywords
- [ ] Installation documentation updated for npm-first workflow

## Dependencies
- **Requires**: #16 (CLI Infrastructure must be complete)
- **Requires**: #17 (Setup Wizard must be implemented)
- **Requires**: #18 (Configuration Management must be working)
- **Enables**: Public distribution and easy installation

## Risk Mitigation
- Test package installation extensively before publishing
- Implement rollback strategy for failed releases
- Monitor package download metrics and error reports
- Maintain backward compatibility with existing installations

## Success Metrics
- Package installs successfully on first attempt: 95%+
- Package size remains under 5MB
- CLI commands work immediately after installation: 100%
- Automated publishing workflow success rate: 99%+
- Time from release to available on npm: < 10 minutes

## Post-Publishing Tasks
- Monitor npm download metrics
- Track and resolve installation issues
- Update documentation based on user feedback
- Plan for package maintenance and updates
